# Site wide configuration

title: Rami Taibah Website
locale: en_US
description: My Life; Online 
logo: site-logo.png
search: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Jekyll configuration

permalink:   /:categories/:title/
#
# Build settings
markdown:    kramdown
highlighter: pygments
theme: minima

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Rami Taibah 
  avatar: bio-photo.jpg
  email: taibah@gmail.com 
  disqus-shortname:
  twitter: rtaibah
  facebook: rtaibah
  github: rtaibah
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: +RamiTaibah
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
